### PR TITLE
API changes  for libva 2.0.0

### PR DESCRIPTION
**Pull request by xhaihao**
This patch series includes the follow changes:
*  Fix a typo in VAConfigAttribValEncROI
*  Update VAEncMacroblockParameterBufferH264
*  Update the data structure for HEVC decoding
*  dec/VC1: Update the comment for b_picture_fraction
*  Deprecate va_tpi.h and va_egl.h
*  Deprecate packed misc packed header
*  Use portable portable types for VA structures

### CODE REVIEW

**Comment by xhaihao** [comment]
https://cgit.freedesktop.org/vaapi/pvr-driver/ supports tpi and egl, but I don't know whether there is user using this driver now.

**Comment by xhaihao** [comment]
Rebased the patches against the latest v2.0-branch

**Comment by ceyusa** [comment]
> https://cgit.freedesktop.org/vaapi/pvr-driver/ supports tpi and egl, but I don't know whether there is user using this driver now.

We shall deprecate all those backends. Nobody are maintaining them.

**Comment by xhaihao** [comment]
1) Rebased the PR against the latest v2.0-branch
2) Remove libva-tpi and libva-egl but keep va_egl.h and va_tpi.h with a deprecation warning message only
3) Remove the comment about vaGetSurfaceAttributes() because vaGetSurfaceAttributes() was removed a few years ago

**Pull request merged**
