### PR TITLE
test: remove from library

### LINKED ISSUE #12: test : Deprecate test folder in favor of libva-utils
Test support has been moved to libva-utils, so remove it.

### PR DESCRIPTION
**Pull request by seanvk**
Moved to libva-utils

Fixes #12

Signed-off-by: Sean V Kelley <seanvk@posteo.de>

### CODE REVIEW

**Comment by seanvk** [comment]
@uartie ping

**Comment by uartie** [comment]
The libva.spec file looks pretty old so perhaps we should just remove it?

**Comment by seanvk** [comment]
Yeah, I filed a separate issue to remove it good call.  I'll add it to the series.

**Comment by seanvk** [comment]
Added removal of libva.spec patch to the series @uartie

**Comment by uartie** [comment]
github says "only reviews by reviewers with write access count toward mergeability"... so apparently I must not have write access to make my review count.

**Comment by seanvk** [comment]
We'll fix that review requirement..  Thanks for the review.

**Pull request merged**
