### PR TITLE
android: move libva-android to /vendor

### PR DESCRIPTION
**Pull request by cwhuang**
This was missed in the previous commit bed97ef.

### CODE REVIEW

**Comment by xhaihao** [comment]
Could you squash the commits in https://github.com/01org/libva/pull/46 and https://github.com/01org/libva/pull/47 into one commit ?

**Comment by cwhuang** [comment]
Oh! I didn't notice Linda posted a similar patch in #46. But it's still incomplete.
Actually #47 has contained the change of #46 .

**Comment by xuguangxin** [comment]
Hi @cwhuang and @LindaYu17 
I only push libva and libva-android to board . The sample_decod is working.
Do we really need libva-tpi and libva-egl?

**Comment by cwhuang** [comment]
Hi @xuguangxin,
It just make the change (move libs to /vendor) complete.
I'm not sure when or how they are used.

Or do you suggest to remove them at all if they are unnecessary?

**Comment by xuguangxin** [comment]
Hi cwhuang:
@LindaYu17  correct me if I am wrong.
This is unnecessary, please help remove it. But the tpi headers used by our internal object. I do not know the header install details, please do not remove it from headers.
thanks

**Comment by xhaihao** [comment]
Both libva-tpi and libva-egl should not be used any more.  libva provides a unified mechanism of sharing buffers with the third party library.  We can merge this change because some applications on android still includes the libva-tpi and libva-egl headers. However it would be better that android team can remove the dependency on libva-tpi and libva-egl, we will deprecate the use of libva-tpi and libva-egl.

**Comment by cwhuang** [comment]
OK. I've updated the patches to remove rules of libva-tpi and libva-egl.

**Pull request merged**
